#!/usr/bin/env bash

#cd ~
#git clone https://github.com/jwrr/lued.git .lued
#cd .lued

git submodule init
git submodule update

echo "*** Apply patch to Lua 5.2"
pushd src/lua/src
git apply ../0001-Minor-changes-to-embed-lua-into-lued.patch
popd

pushd src/carr/src
rm lua_hacked.c lua.h
popd

# Create new build directory
rm -rf build
mkdir build

echo "*** Build lued executable by running cmake and make"
pushd build
cmake ..
make
popd

echo "*** Copy lued executable to top directory"
if [ -f build/lued ]; then
  echo "SUCCESS! 'lued' executable created in current directory"
  cp build/lued .
else 
  echo "ERROR - lued failed to build"
fi


